netfilter: Fix multicast flow is not applied SNAT correctly
This change fixes up compilation error which got dropped
while adding above patch commit* b319162
we observe these errors with default profile or when qca-mcs
module is not enabled.

error snippet:
  CC [M]  net/ipv4/netfilter/nf_nat_l3proto_ipv4.o
In file included from net/ipv4/netfilter/nf_nat_l3proto_ipv4.c:28:0:
include/net/netfilter/br_netfilter.h: In function 'nf_bridge_alloc':
include/net/netfilter/br_netfilter.h:8:5: error: 'struct sk_buff' has no member named 'nf_bridge'
  skb->nf_bridge = kzalloc(sizeof(struct nf_bridge_info), GFP_ATOMIC);

Change-Id: I7efc2d61f7c5937a5b44dc9768a13ee8c56307b6
Signed-off-by: Ram Chandra Jangir <rjangir@codeaurora.org>