dwc3-of-simple: Fix debug build failure
Using dwc3_trace in an inline function causes the below error
in debug builds. To avoid the error new function is written to
handle this.

ERROR: "__tracepoint_dwc3_readl" [drivers/usb/dwc3/dwc3-of-simple.ko] undefined!

Change-Id: Ia654a10a85780b0d2939ac91779c0c28939625af
Signed-off-by: Vasudevan Murugesan <vmuruges@codeaurora.org>