INTERNAL: Add Remoteproc, PDC reset driver support
UPSTREAM: remoteproc: q6v5: Extract common resource handling

Shared between all Hexagon V5 based remoteprocs is the handling of the 5
interrupts and the SMP2P stop request, so break this out into a separate
function in order to allow these drivers to be cleaned up.

Reviewed-by: Rohit kumar <rohitkr@codeaurora.org>
Tested-by: Rohit kumar <rohitkr@codeaurora.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 3b415c8fb263173a60e12666213073c9653737d0)

BUG=b:74016027
TEST=Build and boot

Change-Id: I3f52e7bf42e95abf2a5009d5dce68a0443583ffd

UPSTREAM: remoteproc: qcom: adsp: Use common q6v5 helpers

Migrate the Hexagon V5 PAS (ADSP) driver to using the newly extracted
helper functions. The use of the handover callback does introduce latent
disabling of proxy resources. But apart from this there should be no
change in functionality.

Reviewed-by: Rohit kumar <rohitkr@codeaurora.org>
Reviewed-by: Sricharan R <sricharan@codeaurora.org>
Tested-by: Rohit kumar <rohitkr@codeaurora.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 6103b1a616ab010edddd9a60542df86fd47eb46b)

BUG=b:74016027
TEST=Build and boot

Change-Id: Ic5a60cc0213f14583f9af6dd868a04f085e259c7
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: qcom: q6v5-pil: Use common q6v5 helpers

Migrate the MSS remoteproc driver to use the newly extracted helper
functions.

Reviewed-by: Sricharan R <sricharan@codeaurora.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 7d674731f36c2b3f2707baad6c01cce93c754edf)

BUG=b:74016027
TEST=Build and boot

Change-Id: I9420f2869f6b1ea110ea667528cb8839cd000c96
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: qcom: Introduce Hexagon V5 based WCSS driver

IPQ8074 has an integrated Hexagon dsp core q6v5 and a wireless lan
(Lithium) IP. An mdt type single image format is used for the
firmware. So the mdt_load function can be directly used to load
the firmware. Also add the relevant resets required for this core.

Acked-by: Rob Herring <robh@kernel.org> (bindings)
Signed-off-by: Sricharan R <sricharan@codeaurora.org>
[bjorn: Rewrote as a separate driver, intead of extending q6v5_pil.c]
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 3a3d4163e0bfde184ffbc54c887f5b1ec9969c90)

BUG=b:74016027
TEST=Build and boot

Change-Id: I844baea2893ffa80bda9dc2ee2c7d0b9e32c66d8
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: Rename subdev functions to start/stop

"start" and "stop" are more suitable names for how these two operations
are used, and they fit better with the upcoming introduction of two
additional operations in the struct.

Tested-by: Fabien Dessenne <fabien.dessenne@st.com>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
[elder@linaro.org: minor comment edits]
Signed-off-by Alex Elder <elder@linaro.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 618fcff3742b4c62fea24bea1f01a2f002ed4b37)

BUG=b:74016027
TEST=Build and boot

Change-Id: I1a39c5a8d8bf3413dd0544462d2e2f7795915d9f
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: Make start and stop in subdev optional

Some subdevices, such as glink ssr only care about the stop operation,
so make the operations optional to reduce client code.

Tested-by: Fabien Dessenne <fabien.dessenne@st.com>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
Signed-off-by Alex Elder <elder@linaro.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit be37b1e0fb100a369cfb7ebf016491dfb6c71987)

BUG=b:74016027
TEST=Build and boot

Change-Id: Ieefebe1085e7023a7a04d533bcc1e53290c6b321
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: Make client initialize ops in rproc_subdev

In preparation of adding the additional prepare and unprepare operations
make the client responsible for filling out the function pointers of the
rproc_subdev. This makes the arguments to rproc_add_subdev() more
manageable, in particular when some of the functions are left out.

Tested-by: Fabien Dessenne <fabien.dessenne@st.com>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
[elder@linaro.org: added comment about assigning function pointers]
Signed-off-by Alex Elder <elder@linaro.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 4902676f04acc20fe12e49f5f4916f2659c2a7bc)

BUG=b:74016027
TEST=Build and boot

Change-Id: Ib7a664268ff2aa3751c44df4a5703589bd4c2541
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: rename subdev probe and remove functions

Rename functions used when subdevices are started and stopped to
reflect the new naming scheme.

Tested-by: Fabien Dessenne <fabien.dessenne@st.com>
Signed-off-by Alex Elder <elder@linaro.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 6f8b037308ea7511191b8280efc9d0d5b46c74fe)

BUG=b:74016027
TEST=Build and boot

Change-Id: I4651eeeb6272a9c6ed327e334739ab5726db620d
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: Introduce prepare and unprepare for subdevices

On rare occasions a subdevice might need to prepare some hardware
resources before a remote processor is booted, and clean up some
state after it has been shut down.

One such example is the IP Accelerator found in various Qualcomm
platforms, which is accessed directly from both the modem remoteproc
and the application subsystem and requires an intricate lockstep
process when bringing the modem up and down.

Tested-by: Fabien Dessenne <fabien.dessenne@st.com>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
[elder@linaro.org: minor description and comment edits]
Signed-off-by Alex Elder <elder@linaro.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit c455daa4af3c3ee6e841fc9ed42024d6b8d50d66)

BUG=b:74016027
TEST=Build and boot

Change-Id: I5611c52abddfd6b60b4f91a6db06024f0f1b495e
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: qcom q6v5: fix modular build

The new driver only works as built-in code at the moment but fails
with a link error when configured as a loadable module:

WARNING: modpost: missing MODULE_LICENSE() in drivers/remoteproc/qcom_q6v5.o
see include/linux/module.h for more information
ERROR: "qcom_q6v5_init" [drivers/remoteproc/qcom_q6v5_pil.ko] undefined!
ERROR: "qcom_q6v5_wait_for_start" [drivers/remoteproc/qcom_q6v5_pil.ko] undefined!
ERROR: "qcom_q6v5_prepare" [drivers/remoteproc/qcom_q6v5_pil.ko] undefined!
ERROR: "qcom_q6v5_unprepare" [drivers/remoteproc/qcom_q6v5_pil.ko] undefined!
ERROR: "qcom_q6v5_request_stop" [drivers/remoteproc/qcom_q6v5_pil.ko] undefined!
ERROR: "qcom_q6v5_init" [drivers/remoteproc/qcom_adsp_pil.ko] undefined!
ERROR: "qcom_q6v5_wait_for_start" [drivers/remoteproc/qcom_adsp_pil.ko] undefined!
ERROR: "qcom_q6v5_prepare" [drivers/remoteproc/qcom_adsp_pil.ko] undefined!
ERROR: "qcom_q6v5_unprepare" [drivers/remoteproc/qcom_adsp_pil.ko] undefined!
ERROR: "qcom_q6v5_request_stop" [drivers/remoteproc/qcom_adsp_pil.ko] undefined!

This exports the internal symbols as needed and adds the MODULE_LICENSE()
and MODULE_DESCRIPTION() tags. I could not figure out the author, so I
did not add a MODULE_AUTHOR() tag for now.

Fixes: 3b415c8fb263 ("remoteproc: q6v5: Extract common resource handling")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit ded79d06986e62da1376ae1a62627a36ecbf9ee6)

BUG=b:74016027
TEST=Build and boot

Change-Id: I7c6c3ac41eff95f27ed945ab436ed42c25d2750a
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: qcom: q6v5-pil: fix modem hang on SDM845 after axis2 clk unvote

GCC_MSS_AXIS2 clock is used for disabling boot IMEM (a part of
AP boot up). With Boot IMEM disable now a part TZ/ATF, AXIS2
clock is no longer required post AP boot up and expected to
remain untouched. However if the clock is turned ON after Q6
is brought out of reset and later turned off, it results in
modem hang. When Q6 attempts a power collapse the internal
handshaking to check if AXIS2 is idle never goes through since
it is turned off preventing the RSC from getting triggered,
leaving modem in a funky state. Hence removing AXIS2 clk
enable/disable from the driver.

Reported-by: Bjorn Andersson <bjorn.andersson@linaro.org>
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 7cbb540a3a68e4d4a8bef2d9451afb1635b5d2d3)

BUG=b:74016027
TEST=Build and boot

Change-Id: I3a9f51ecacaaf4f8f8832bf9afef70f29991a197
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: Reset table_ptr in rproc_start() failure paths

Unwind the modified table_ptr and restore it to the local copy
upon any subsequent failures in the rproc_start() function. This
keeps the function to remain balanced on failures without the need
to balance any modified variables elsewhere.

While at this, do some minor cleanup of the extra lines between
the failure labels as well.

Signed-off-by: Suman Anna <s-anna@ti.com>
[bjorn: unconditionally set table_ptr to cached_table]
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit f68d51bd8a7141ba84f06e6207197817398e7f3a)

BUG=b:74016027
TEST=Build and boot

Change-Id: I9171659be1a610381e399b65b5805a8ac846656d
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

UPSTREAM: remoteproc: qcom: fix Q6V5_WCSS dependencies

A new driver got added that depends on QCOM_SMD and fails to link
as built-in with CONFIG_QCOM_SMD=m:

drivers/remoteproc/qcom_common.o: In function `smd_subdev_stop':
qcom_common.c:(.text+0x674): undefined reference to `qcom_smd_unregister_edge'
drivers/remoteproc/qcom_common.o: In function `smd_subdev_start':
qcom_common.c:(.text+0x700): undefined reference to `qcom_smd_register_edge'

We've fixed the same thing several times before, so use the same
dependency here.

Fixes: 3a3d4163e0bf ("remoteproc: qcom: Introduce Hexagon V5 based WCSS driver")
Acked-by: Sricharan R <sricharan@codeaurora.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 12c2b509c0cb981b34771097e4769abc7faebcee)

BUG=b:74016027
TEST=Build and boot

Change-Id: I9367dad75f29d3091fead706665a8f2d46f5306c
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

FROMLIST: remoteproc: Introduce custom dump function for each remoteproc segment

Introduce custom dump function per remoteproc segment. It is responsible
for filling the device memory segment associated with coredump

Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
(am from https://patchwork.kernel.org/patch/10547323/)
(also found at https://lkml.kernel.org/r/20180727152003.11663-2-sibis@codeaurora.org)

BUG=b:74016027
TEST=Build and boot

Change-Id: I661713a06c719cf13bf61a36666238984128dcd3
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

FROMLIST: remoteproc: Add mechanism for custom dump function assignment

This patch adds a mechanism for assigning each rproc segment with
a custom dump function. It is to be called for each rproc segment
during coredump if assigned.

Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
(am from https://patchwork.kernel.org/patch/10547327/)
(also found at https://lkml.kernel.org/r/20180727152003.11663-3-sibis@codeaurora.org)

BUG=b:74016027
TEST=Build and boot

Change-Id: Icc0ff86bd9973119bbf340bd46c15e837657dc56
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

BACKPORT: FROMLIST: remoteproc: qcom: q6v5-pil: Refactor mba load/unload sequence

Refactor re-useable parts of mba load/unload sequence into mba_load and
mba_reclaim respectively and introduce mba_load flag. This is done in
order to prevent code duplication for modem coredump which requires the
mba to be loaded.

Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
(am from https://patchwork.kernel.org/patch/10547333/)
(also found at https://lkml.kernel.org/r/20180727152003.11663-4-sibis@codeaurora.org)

Signed-off-by: Atul Dhudase <adhudase@codeaurora.org>

Conflicts:
   drivers/remoteproc/qcom_q6v5_pil.c

BUG=b:74016027
TEST=Build and boot

Change-Id: Ie95001792676bc0f9a5ab67eb2f21b430d6fc0f7
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

FROMLIST: remoteproc: qcom: q6v5-pil: Add custom dump function for modem

The per segment dump function is responsible for loading the mba
before device memory segments associated with coredump can be populated
and for cleaning up the resources post coredump.

Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
(am from https://patchwork.kernel.org/patch/10547345/)
(also found at https://lkml.kernel.org/r/20180727152003.11663-5-sibis@codeaurora.org)

BUG=b:74016027
TEST=Build and boot

Change-Id: Ie24e69fbd08bbeb180d97f0517805612da5fcffa
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

FROMLIST: remoteproc: qcom: q6v5-pil: Register segments/dumpfn for coredump

Register the MDT segments and custom dumpfn with the remoteproc core
dump functionality.

Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
(am from https://patchwork.kernel.org/patch/10547339/)
(also found at https://lkml.kernel.org/r/20180727152003.11663-6-sibis@codeaurora.org)

BUG=b:74016027
TEST=Build and boot

Change-Id: I26fd9c5af3eea6ecd45b63276da159fdd383e41b
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

FROMLIST: remoteproc: qcom: q6v5-pil: Assign the relocated address

Assign the relocated base of the modem image, as the offsets
from the virtual memory might not be based on the physical
address.

Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
(am from https://patchwork.kernel.org/patch/10547335/)
(also found at https://lkml.kernel.org/r/20180727152003.11663-7-sibis@codeaurora.org)

BUG=b:74016027
TEST=Build and boot

Change-Id: I56be1fe33fc37d4acb8a2b92e33a133ac0918d5b
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

INTERNAL: remoteproc: Add ramdump/live debug support for modem

Live Debug is enabled by writing required magic number to
qcom,msm-imem-pil base address. Also write image info struct
to qcom,msm-imem-pil base address to enable Ramdump support.

This patch is based on Yossi Mansharoff <yossim@codeaurora.org>
patch series with additional fixes.

Change-Id: I8644ec8ee7b7e6e088d41d7fe4ee34f256728983
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

INTERNAL: arm64: dts: Add SDM845 Imem node for pil

Add imem node with pil offset to enable live debug
and ramdump support for modem

Change-Id: I016ff97fe17dd8ed672cda2da97573cf70c5ff4c
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

FROMLIST: dt-bindings: reset: Add PDC Global binding for SDM845 SoCs

Add PDC Global(Power Domain Controller) binding for SDM845 SoCs.

Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
(am from https://patchwork.kernel.org/patch/10575333/)

BUG=b:74016027
TEST=Build and boot

Change-Id: Ifd0fe56d6ea0e0a46d1b23406e222713cfad7f41
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

BACKPORT: FROMLIST: reset: qcom: PDC Global (Power Domain Controller) reset controller

Add reset controller for SDM845 SoCs to control reset signals provided
by PDC Global for Modem, Compute, Display, GPU, Debug, AOP, Sensors,
Audio, SP and APPS

Signed-off-by: Sibi Sankar <sibis@codeaurora.org>
(am from https://patchwork.kernel.org/patch/10575343/)

Conflicts:
   drivers/reset/Kconfig
   drivers/reset/Makefile

BUG=b:74016027
TEST=Build and boot

Change-Id: I92355e2d089f0957075d2d949b9221704a9af88d
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

INTERNAL: arm64: dts: Add PDC global node

Add PDC Global (Power Domain Controller) node for
SDM845 SoCs

Change-Id: I7a5f9c98132c19a930a9c8203cb9cb7dd212a3e6
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>

CHROMIUM: config: Turn on PDC Global reset controller

This is the equivalent of:

echo 'CONFIG_RESET_QCOM_PDC=y' | tee -a \
        chromeos/config/arm64/chromiumos-qualcomm.flavour.config \
	chromeos/config/arm64/chromiumos-arm64.flavour.config
	./chromeos/scripts/kernelconfig olddefconfig

Change-Id: I35991733970b068faffc953ef2aaeb42a018b139
Signed-off-by: Atul Dhudase <adhudase@codeaurora.org>

UPSTREAM: remoteproc: qcom: mdt_loader: Make the firmware authentication optional

qcom_mdt_load function loads the mdt type firmware and
initialises the secure memory as well. Make the initialisation only
when requested by the caller, so that the function can be used
by self-authenticating remoteproc as well.

Acked-by: Andy Gross <andy.gross@linaro.org>
Signed-off-by: Sricharan R <sricharan@codeaurora.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 0e622e80191e75c99b6ecc265c140a37d81e7a63)

BUG=b:74016027
TEST=Build and boot

Change-Id: I3fc51ea4be5d03ff68733d9106098a394b1ccd56
Signed-off-by: Sibi Sankar <sibis@codeaurora.org>